name: deploy-arm64-snap

on:
  workflow_run:
    workflows:
      - build-arm64-snap
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: [self-hosted, arm64-server-1]

    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

    steps:
      - name: deploy
        run: |
          snapcraft upload $(realpath /tmp/ci-artifacts-arm64/wick_*.snap) --release edge
